### PR TITLE
Create new winston logger only once for each option set

### PR DESCRIPTION
**Pull request by didebeach**
Just a different approach by creating only once the real winston logger for each Option set.

Again this Version is working for me as it solves my Problem with the "Memory leak" and still supports meta data for every request.

### CODE REVIEW

**Comment by ryan-roemer** [comment]
This doesn't work because objects only take string keys, and the string representation of any object is `"[object Object]"`

So you are effectively doing the following:

```js
interalLoggerHash["[object Object]"] = foo;
interalLoggerHash["[object Object]"] = bar;
interalLoggerHash["[object Object]"] = baz;
```

Which is obviously not what we want. Closing this PR to re-examine the original issue.

**Comment by didebeach** [comment]
I understand, but the Idea should be working. either by creating a hash from the object or using the JSON String of the object.
:-)

**Comment by ryan-roemer** [comment]
@didebeach -- You can try a `interalLoggerHash[JSON.stringify(obj)]` for the hash, but my strong intuition there is you will run into exactly the same problem as you see before. The main difference with your approach is you only maintain **one** log instance above, and incorrectly.

The best way out of this is to get me a reproduction setup and I'll debug it further...

**Comment by didebeach** [comment]
What I do is that I create only a single eventhandler for a specific type of log interaction (file, console etc.)

The Point that I don't understand: 
what is the benefit of creating always a fresh log interaction that do exact the same instead of recycle a already created log intance. There is nothing else connected (as fare as I understand) with the  logger as described in the Options for the logger.

I understand that this is primary a problem of the winston module as the event handler will be not removed as required. But that is just my Assumtion of the underlyning problem.

used now the stringify solution and it works again for me :-)
  var key = JSON.stringify(opts);
  if (interalLoggerHash[key] == null) {
    // Create internal, real Winston logger.
    console.log('New logger for options: ' + key);
    var log = new winston.Logger(opts);
    interalLoggerHash[key] = log;
  }
  this._log = interalLoggerHash[key];

**Comment by ryan-roemer** [comment]
Sorry, I didn't fully grok the code. You're still creating a smaller number singletons.

The main point here is the whole point of the request logger is a new one for each request because we do something like:

* Attach request `{ sourceIp: 44.44.4.4 }` to the metadata for Request "1"
* Attach response `{ status: 404 }` to the metadata for Request "1"

If you interleave "Request 2" in there the metadata is inconsistent. There _will_ need to be a separate logger to deal with the skew between request information starting and response coming after (especially for apps with long i/o or multiple middlewares).

Please create a unit of code I can run and reproduce the issue and I'll work hard to get to the bottom of the issue. Thanks!

**Comment by didebeach** [comment]
I do undestand this point. Let ask me the other way arround.
If you create a new winston log instance with options what does it mean: (example write into a file)
-->for me the return value of the new winston is an instance that allows me to write down into that file a text every time I use the instance.info method

Your approach, and I like it as I now start to understand it a little, is just to add standarsized information or specific information to a request that you may use on a later stage or in a different middleware.

If I'm not complete wrong this is done with the Log instance inside of the index.js file. So the encapsulation of this information is hosted inside of the log instance.

and still there is the same "logfile" required to write into as we decide the type of logging with the options for winston.

Sorry to "spam" you with my comments but it's so interesting for me to figure out where could be my wrong interpretation.

Awaiting your feedback from my little demo code and still hope to not haveing a to stupid mistake done in my code

**Pull request closed without merging**
