### PR TITLE
Add transformMeta function

### PR DESCRIPTION
**Pull request by zianwar**
References #12

### CODE REVIEW

**Comment by ryan-roemer** [comment]
@Zianwar -- This is generally looking good. the one ambiguity / complication are these lines: https://github.com/FormidableLabs/express-winston-middleware/blob/master/index.js#L130-L132

The library models the connect logger middleware in monkeypatching `res.end()` to get access to the actual status code (which you normally can't in middleware) so that we can add something like: 

```js
  "res": {
    "statusCode": 200
  },
````

This also means for the transform function that if you are using the request middleware you _cannot_ remove that field (and the things like `date`, `level`, `message`. Is that acceptable?

If so, I'll just add a note to the function comment and update your PR...

**Comment by Zianwar** [comment]
@ryan-roemer yeah I see, do you think that we can do something in order to get around this? if not I'm okay with it. :)

**Comment by ryan-roemer** [comment]
@Zianwar -- So I retooled the transform function to be stashed and **delayed** and then execute during the actual log calls. So this needs to be set once, then will apply right before the underlying winston call. This makes it slightly harder to reason about, but is nice because it's after **all** the metadata is added. Here's how it looks now:

```js
/**
 * `Log.transformMeta(fn)`
 *
 * Set a delayed single transform function to mutate a **copy** of the metadata
 * _right before_ a logging event. You can only presently have **one** such
 * function. And it is delayed so that for things like request end, you can
 * effectively access **all** the metadata.
 *
 * The transform is applied on each log call and passes a copy of the mutated
 * metadata to the actual log call.
 *
 * The function signature should be `fn(existingMeta)` and return mutated
 * metadata.
 *
 * @param {Function} fn Transform function.
 * @api public
 */
Log.prototype.transformMeta = function (fn) {
  this._metaTransformFn = fn;

  return this;
};
```

Thanks for working through this and hope this last tweak works for your uses!

**Comment by ryan-roemer** [comment]
Released in `express-winston-middleware@0.1.0`

**Comment by Zianwar** [comment]
Awesome, now I can log and customise the whole request lifecycle even the response body, and that's what I wanted.

@ryan-roemer thank you for your great support and for giving me the chance to contribute to this project :)

**Pull request merged**
